INFO     /Users/yixia/PycharmProjects/iosmiaopai/logs/log.txt:IMP_login.py:236 ========star app=========
WARNING  urllib3.connectionpool:connectionpool.py:662 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11383b208>: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:662 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11383b3c8>: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:662 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11383b5c0>: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session